version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.5.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=kabir123
      - xpack.security.enabled=true

    network_mode: bridge
    ports:
      - '9200:9200'
      - '9300:9300'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './es_data:/usr/share/elasticsearch/data'
          
  kibana:
    container_name: kibana
    image: kibana:7.5.0
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    network_mode: bridge
    environment: 
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=kabir123

    ulimits:
      memlock:
        soft: -1
        hard: -1
  logstash:
    container_name: logstash
    image: logstash:7.5.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    network_mode: bridge

    ulimits:
      memlock:
        soft: -1
        hard: -1
            
  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.5.0
    links:
      - logstash:logstash
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /home/alamgir/Desktop/layout:/usr/local/layout/logs
    command: ["--strict.perms=false"]
    stdin_open: true
    network_mode: bridge
    deploy:
      mode: global
